//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACKEND.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class relAlertUser
    {
        public System.Guid ID { get; set; }
        public System.Guid alertID { get; set; }
        public System.Guid userID { get; set; }
    
        public virtual tblAlert tblAlert { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
