//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACKEND.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class relEntriesDescription
    {
        public System.Guid ID { get; set; }
        public System.Guid descriptionID { get; set; }
        public System.Guid entryID { get; set; }
    
        public virtual tblEntries tblEntries { get; set; }
        public virtual tblEntryDescription tblEntryDescription { get; set; }
    }
}
