//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACKEND.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccess
    {
        public System.Guid ID { get; set; }
        public int isReadAndWrite { get; set; }
        public System.Guid userID { get; set; }
        public System.Guid groupID { get; set; }
        public System.DateTime dateAdded { get; set; }
        public System.DateTime dateModified { get; set; }
        public string nameUser { get; set; }
    
        public virtual tblGroup tblGroup { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
