//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACKEND.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAlert()
        {
            this.relAlertUser = new HashSet<relAlertUser>();
        }
    
        public System.Guid ID { get; set; }
        public string Nome { get; set; }
        public string textAlert { get; set; }
        public System.DateTime dateTimeAlert { get; set; }
        public System.DateTime dateAdded { get; set; }
        public System.DateTime dateModified { get; set; }
        public string nameUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relAlertUser> relAlertUser { get; set; }
    }
}
