//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACKEND.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntryDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEntryDescription()
        {
            this.relEntriesDescription = new HashSet<relEntriesDescription>();
        }
    
        public System.Guid ID { get; set; }
        public int Sequence { get; set; }
        public string Description { get; set; }
        public System.DateTime dateAdded { get; set; }
        public System.DateTime dateModified { get; set; }
        public string nameUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relEntriesDescription> relEntriesDescription { get; set; }
    }
}
