//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACKEND.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.relAlertUser = new HashSet<relAlertUser>();
            this.tblAccess = new HashSet<tblAccess>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Comments { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Provider { get; set; }
        public System.Guid Session { get; set; }
        public string Token { get; set; }
        public System.DateTime dateIssued { get; set; }
        public System.DateTime dateCreated { get; set; }
        public System.DateTime dateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<relAlertUser> relAlertUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccess> tblAccess { get; set; }
    }
}
